version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - run: npm install
      - run:
        name: "build react app"
        command: |
          npm run build
      - env:
        CI: ""

      - add_ssh_keys:
        fingerprints:
          - "5f:df:06:ff:6a:97:64:1f:b1:15:a6:06:a8:d7:3f:b5"
      - run:
        name: Deploy Over SSH
        command: |
          scp -r -o StrictHostKeyChecking=no ~/project/build/* $SSH_USER@$SSH_TARGET

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
