version: 2.1

orbs:
  rsync: aplazame/rsync@0.0.17

jobs:
  build:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - run: npm install
      - run:
          name: "build react app"
          command: |
            PUBLIC_URL=https://remappingcomancheria.com npm run build
          environment:
            CI: ""

      - add_ssh_keys:
          fingerprints:
            - $SSH_FINGERPRINT
      - run:
          name: Deploy Over SSH
          command: |
            rsync -avce ssh ~/project/build/. $SSH_USER@$SSH_TARGET

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
