version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - run: npm install
      - run:
          name: "build react app"
          command: |
            npm run build
          environment:
            CI: ""

      - add_ssh_keys:
          fingerprints:
            - "30:78:d8:8c:f3:19:bd:95:b9:5c:6c:15:44:a9:42:a8"
      - run:
          name: Deploy Over SSH
          command: |
            scp -r -o StrictHostKeyChecking=no ~/project/build/* $SSH_USER@$SSH_TARGET

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
